name: Jekyll Deploy to Multiple Domains

on:
  push:
    branches:
      - rue
      - com

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install

      - name: Determine branch and config
        id: branch_config
        run: |
          BRANCH=${GITHUB_REF##*/}
          CONFIG="_config.${BRANCH}.yml"
          echo "::set-output name=branch::$BRANCH"
          echo "::set-output name=config::$CONFIG"

      - name: Build Jekyll site
        run: bundle exec jekyll build --config ${{ steps.branch_config.outputs.config }}

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: _site
          cname: ${{ steps.branch_config.outputs.branch == 'rue' && 'statichun.ru' || 'statichun.com' }}
          user_name: github-actions[bot]
          user_email: github-actions[bot]@users.noreply.github.com
          commit_message: "Deploy from ${{ steps.branch_config.outputs.branch }} branch"
